### ISSUE TITLE
Feature request: 'allow' and 'disallow' for 'numeric'

### ISSUE THREAD

**Issue by kdex** [KevinSheedy/jquery.alphanum#22]
As you can see in the following snippet, it's a little awkward to exclude a great part of the alpahet (even twice, since the _force_ options are currently broken).

```
$("#colorInput").alphanum({
    disallow: "GHIJKLMNOPQRSTUVWXYZghijklmnopqrstuvwxyz",
    allow: "#",
});
```

That's why I'd like to ask for an equivalent construct such as:

```
$("#colorInput").numeric({
    allow: "ABCDEFabcdef#",
});
```

Does your implementation allow for such an idea?

**Comment by retzion** [comment]
I haven't successfully been able to allow the "$" char to be entered. I

{ allow : '$' }
should work or not for .numeric() ?

**Comment by nitinjs** [comment]
How do I disallow 0?

e..g 0 is invalid
and 00 is invalid

100 is valid
200 is valid

**Comment by kdex** [comment]
Closing as I have lost my interest in this project.
