### ISSUE TITLE
Disabled Fields

### ISSUE THREAD

**Issue by audas** [KevinSheedy/jquery.alphanum#30]
Allow for change events to fire in disabled fields so that the can be populated with content and be controlled with alphanum.

**Comment by KevinSheedy** [comment]
@audas I'm afraid I don't understand. Are you trying to populate disabled fields? This is prevented by the browser.

**Comment by KevinSheedy** [comment]
Hi @audas. I'm closing this one as I don't have enough enough and don't understand the problem. Let me know if you want to provide more info and open it again. Thanks
