### ISSUE TITLE
In numericField_Blur setting is undefined

### ISSUE THREAD

**Issue by rvimal** [KevinSheedy/jquery.alphanum#31]
![image](https://cloud.githubusercontent.com/assets/8748180/4248021/dadd8982-3a61-11e4-8cf1-5f0a8256286b.png)

When id is set to only numeric (Ex: $('#accountBalance').numeric();), on blur after entering the value it throughts "Uncaught TypeError: Cannot read property 'min' of undefined "  error. 

//Will below code fixes the bugs 
		$collection.blur(function(){
			//Below is the bug fixing 
			settings=(settings=== undefined)? combinedSettings : settings;
			numericField_Blur(this, settings);
		});

**Comment by prodrigues** [comment]
+1, this issue affects for me too.
Fortunately, i've ended up using a more suitable rule: $('...').numeric('positiveInteger').

**Comment by KevinSheedy** [comment]
Fixed in 1.0.23

**Comment by KevinSheedy** [comment]
Thanks @leesaxby for the PR
