### ISSUE TITLE
Need to be able to rebind an input field to a numeric with different settings

### ISSUE THREAD

**Issue by AndyAdamczak** [KevinSheedy/jquery.alphanum#37]
I have a need where the min and max values change based on a select next to the input field (the option values have data elements for min and max).  I have a need to be able to rebind an input field to a .numeric().  I have written the code that lets me do this, and I'd like to add it to the core plugin code on Github.  How do I go about submitting this?

**Comment by KevinSheedy** [comment]
Hi Andy
You'll need to fork the repo, commit your changes, then create a pull request.
The process is explained [here](https://help.github.com/articles/using-pull-requests/).
Thanks

**Comment by KevinSheedy** [comment]
Fixed in 1.0.19
Calling `.alphanum()` will now unbind previous settings and rebind the new settings.
