### ISSUE TITLE
Can't set a general selector and then over-ride with a more specific selector

### ISSUE THREAD

**Issue by ramasaig** [KevinSheedy/jquery.alphanum#46]
I have set up 'alphanum' for all the inputs on a form, and allowed hyphen and apostrophe (single quote) as I need those for Name and Address fields. Works fine. But I also need to allow @ and . (full stop) for the e-mail input.
I tried
    $('inputs').alphanum( {allow : "-'"} ); and
    $('inputs#email').alphanum( {allow : "-@."} );
but it didn't work. No matter which order the statements were in I could not get an '@' in my e-mail field.

I was successful with an exclusion in the first statement:
    $('inputs').not('#email').alphanum( {allow : "-'"} ); and 
    $('inputs#email').alphanum( {allow : "-@."} );

In general the arrangement with a general selector followed by a more specific one seems to work, so would it be possible to make it work in 'alphanum', please ?

**Comment by KevinSheedy** [comment]
This sounds reasonable. Should be possible using the namespace feature of the jquery .bind() function.

**Comment by KevinSheedy** [comment]
Fixed in 1.0.19
Calling `.alphanum()` will now unbind previous settings and rebind the new settings.
