### ISSUE TITLE
How we can remove numeric() from a field.

### ISSUE THREAD

**Issue by pawan777** [KevinSheedy/jquery.alphanum#47]
Hi, 

I want to add numeric based on some condition. 

if(true) {
element.numeric();
}else{
element.destroy();
}

Please help how I can do this.

**Comment by KevinSheedy** [comment]
I don't fully understand your question. Do you want to add .numeric() based on a condition? Or do you want to unbind .numeric() from an element after it has already been added?

**Comment by KevinSheedy** [comment]
Fixed in 1.0.19

    $('input').off('.alphanum');
