### ISSUE TITLE
[Fix] Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function. [Solution] Add semicolon to the end of jquery.alphanum.js

### ISSUE THREAD

**Issue by prodrigues** [KevinSheedy/jquery.alphanum#53]
When concatenating the file jquery.alphanum.js with other libraries into a single file, the following error is thrown in chrome's console:

`Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function`

This happens because the minified code of the selection library in the end of the jquery.alphanum.js does not contain a semicolon. The file should end like:
`;e.fn.selection.getCharElement=a})(jQuery);`

**For now, to solve this issue, just make sure the jquery.alphanum.js is the last file concatenated.**

**Comment by KevinSheedy** [comment]
Fixed in 1.0.25
@prodrigues would you be able to test it?

**Comment by prodrigues** [comment]
@KevinSheedy Sure, the version on master is fine now.
